var constants = {
  REGION_CODE:"000000",
  APPCACHE_ACTION_COMPLETE_FLAG2:"APPCACHE_ACTION_COMPLETE_FLAG2",
  APPCACHE_ACTION_INFO2:"APPCACHE_ACTION_INFO2",
  APPCACHE_EDITOR_HTML2:"APPCACHE_EDITOR_HTML2",
  APPCACHE_EDITOR_CONTENTS2:"APPCACHE_EDITOR_CONTENTS2",
  APPCACHE_ENROLL_INFO2:"APPCACHE_ENROLL_INFO2",
  APPCACHE_ACTION_COMPLETE_FLAG: "APPCACHE_ACTION_COMPLETE_FLAG",
  APPCACHE_ACTION_INFO:"APPCACHE_ACTION_INFO",
  APPCACHE_EDITOR_CONTENTS:"APPCACHE_EDITOR_CONTENTS",
  APPCACHE_EDITOR_HTML:"APPCACHE_EDITOR_HTML",
  APPCACHE_ENROLL_INFO: "APPCACHE_ENROLL_INFO",
  APPCACHE:"",
  STKEY_GOODSDETAIL : "STKEY_GOODSDETAIL",
  STKEY_GOODSCATEGORY :"STKEY_GOODSCATEGORY",
  STKEY_STATEINFO:"STKEY_STATEINFO",
  OPERTYPE_GOODSPROMS: "A",//商品有参入活动（作为活动主商品），不包括活动从属商品
  OPERTYPE_GOODSINPROM: "I", //商品有参入活动，包括作为活动组合的一部分（活动从属商品）
  UPIMG_CFG : {
    cloudpath: 'goods',
    compressrate:10,
    maxcount: 4,
    maxwidth: 1242,
    maxheight: 2000,
    cutimg:false,
    cloudid:"xiaovt",
    imgtype: 'jpg'
  }
}

module.exports = constants;